server:
  port: 8090
spring:
  application:
    name: "loans"
  profiles:
    active: "prod"
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: anuj
#    password: ''
#  h2:
#    console:
#      enabled: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/loansdb
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: "optional:configserver:http://configserver:8071"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/

endpoints:
  shutdown:
    enabled: true

build:
  version: "0.0"

info:
  app:
    name: "loans"
    description: "PS Bank Loans Application"
  version: "1.0.0"