build:
  version: "3.0"

accounts:
  message: "Welcome to PS Bank related accounts local APIs"
  contactDetails:
    name: "Anuj Kumar"
    email: "anuj@gmail.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 555-2345