build:
  version: "3.0"

loans:
  message: "Welcome to PS Bank related loans local APIs"
  contactDetails:
    name: "Anuj Kumar"
    email: "anuj@gmail.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 555-2345