spring:
  application:
    name: configserver
  profiles:
#    active: native
    active: git

  cloud:
    config:
      server:
#        native:
#          search-locations: "classpath:/config"
#          search-locations: "file:///C://Configuration//config"
        git:
          uri: "https://github.com/Anjgce/Microservices.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: "45G56H45FHDSJHFJKD687873EA"

server:
  port: 8071

